version: 2
updates:
  - package-ecosystem: npm
    directory: "/backend"
    open-pull-requests-limit: 5
    rebase-strategy: auto
    target-branch: main
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: "/frontend"
    open-pull-requests-limit: 5
    rebase-strategy: auto
    target-branch: main
    schedule:
      interval: daily