services:
  postgres:
    image: postgres:14
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: fortune-bookstore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      PGDATA: /var/lib/postgresql/data/pgdata