import Head from 'next/head';
import { Button, Typography } from '@mui/material';

export default function Home() {
    return (
        <>
            <Head>
                <title>Fortune Bookstore</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Button>test</Button>
            <Typography>test</Typography>
        </>
    );
}
